Library IEEE;
Use IEEE.std_logic_1164.All;

ENTITY MUX is
GENERIC(
N: INTEGER := 1
);
PORT(
A : IN STD_LOGIC_VECTOR(0 TO N);
B : IN STD_LOGIC_VECTOR(0 TO N);
S : IN STD_LOGIC_VECTOR(0 TO N);

G : OUT STD_LOGIC

);
END ENTITY;

ARCHITECTURE BEHAVIORAL OF MUX IS
COMPONENT MUX IS
PORT(
A : IN STD_LOGIC;
B : IN STD_LOGIC;
S : IN STD_LOGIC;

G : OUT STD_LOGIC

);
END COMPONENT;
SIGNAL X: STD_LOGIC_VECTOR(0 TO N);
begin

GenMux: FOR i in 0 to N GENERATE 
MUX1: MUX

PORT MAP(A =>A(0),S => S(i),B => B(i), G => X(i));
X(i) <= A(i+1);

END GENERATE;
G <= X(N);
END BEHAVIORAL;