set_property PACKAGE_PIN W5 [get_ports Cin]
set_property PACKAGE_PIN U18 [get_ports Cin2]
set_property PACKAGE_PIN L1 [get_ports Cout]
set_property IOSTANDARD LVCMOS33 [get_ports Cin]
set_property IOSTANDARD LVCMOS33 [get_ports Cin2]
set_property IOSTANDARD LVCMOS33 [get_ports Cout]

set_property PACKAGE_PIN U16 [get_ports C1]
set_property PACKAGE_PIN E19 [get_ports C2]
set_property PACKAGE_PIN U19 [get_ports C3]
set_property PACKAGE_PIN V19 [get_ports C4]
set_property IOSTANDARD LVCMOS33 [get_ports C3]
set_property IOSTANDARD LVCMOS33 [get_ports C4]
set_property IOSTANDARD LVCMOS33 [get_ports C1]
set_property IOSTANDARD LVCMOS33 [get_ports C2]

set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN U18 [get_ports EN]
set_property PACKAGE_PIN W19 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports EN]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[0]}]

set_property PACKAGE_PIN U16 [get_ports {Q[0]}]
set_property PACKAGE_PIN E19 [get_ports {Q[1]}]
set_property PACKAGE_PIN U19 [get_ports {Q[2]}]
set_property PACKAGE_PIN V19 [get_ports {Q[3]}]
