# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/FPGAHardwareDesign/ProgCLKDivider/ProgCLKDivider.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_2422_0_v_hdmi_rx_0_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2422_0_v_hdmi_rx_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGAHardwareDesign/ProgCLKDivider/ProgCLKDivider.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_2422_0_v_hdmi_rx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2422_0_v_hdmi_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGAHardwareDesign/ProgCLKDivider/ProgCLKDivider.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_2422_0_v_hdmi_rx_0_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2422_0_v_hdmi_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGAHardwareDesign/ProgCLKDivider/ProgCLKDivider.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_2422_0_v_hdmi_rx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2422_0_v_hdmi_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
